apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-lab2-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins-lab2
  template:
    metadata:
      labels:
        app: jenkins-lab2
    spec:
      containers:
      - name: jenkins-project
        image: saeedkouta/Jenkins-project:v1
        ports:
        - containerPort: 5000

